title: JALT PIE SIG
description: Performance in Education Special Interest Group
url: "https://jaltpiesig.org"

theme: jekyll-theme-primer # Or build a completely custom layout using HTML/CSS

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Prevent Jekyll from attempting to parse image assets inside _posts subfolders
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - "_posts/**/images"
  - "_posts/**/*.jpg"
  - "_posts/**/*.jpeg"
  - "_posts/**/*.png"
  - "_posts/**/*.gif"
  - "_posts/**/*.webp"